URLs = {
    "all": "https://www.fantasypros.com/nfl/rankings/consensus-cheatsheets.php",
    "all_ppr": "https://www.fantasypros.com/nfl/rankings/ppr-cheatsheets.php",
    "qb": "https://www.fantasypros.com/nfl/rankings/qb-cheatsheets.php",
    "rb": "https://www.fantasypros.com/nfl/rankings/rb-cheatsheets.php",
    "rb_ppr": "https://www.fantasypros.com/nfl/rankings/ppr-rb-cheatsheets.php",
    "wr": "https://www.fantasypros.com/nfl/rankings/wr-cheatsheets.php",
    "wr_ppr": "https://www.fantasypros.com/nfl/rankings/ppr-wr-cheatsheets.php",
    "te": "https://www.fantasypros.com/nfl/rankings/te-cheatsheets.php",
    "te_ppr": "https://www.fantasypros.com/nfl/rankings/ppr-te-cheatsheets.php",
    "k": "https://www.fantasypros.com/nfl/rankings/k-cheatsheets.php",
    "def": "https://www.fantasypros.com/nfl/rankings/dst-cheatsheets.php",
}

BOOM_BUST_URLs = {
    "qb": "https://www.fantasypros.com/nfl/reports/boom-bust-qb.php",
    "rb": "https://www.fantasypros.com/nfl/reports/boom-bust-rb.php",
    "rb_ppr": "https://www.fantasypros.com/nfl/reports/ppr-boom-bust-rb.php",
    "wr": "https://www.fantasypros.com/nfl/reports/boom-bust-wr.php",
    "wr_ppr": "https://www.fantasypros.com/nfl/reports/ppr-boom-bust-wr.php",
    "te": "https://www.fantasypros.com/nfl/reports/boom-bust-te.php",
    "te_ppr": "https://www.fantasypros.com/nfl/reports/ppr-boom-bust-te.php",
}

BOOM_BUST_COLUMNS = [
    "PLAYER NAME",
    "GAMES",
    "BOOM",
    "STARTER",
    "BUST",
    "PPR_BOOM",
    "PPR_STARTER",
    "PPR_BUST",
]

RANK_DF_COLUMNS = {
    "all": ["PLAYER NAME", "TEAM", "BEST", "WORST", "AVG.", "STD.DEV"],
    "all_ppr": [
        "PPR_RK",
        "PPR_TIERS",
        "PLAYER NAME",
        "TEAM",
        "PPR_BEST",
        "PPR_WORST",
        "PPR_AVG.",
        "PPR_STD.DEV",
    ],
    "qb": [
        "POS_RK",
        "POS_TIERS",
        "PLAYER NAME",
        "TEAM",
        "POS_BEST",
        "POS_WORST",
        "POS_AVG.",
        "POS_STD.DEV",
    ],
    "rb": ["PLAYER NAME", "TEAM", "POS_BEST", "POS_WORST", "POS_AVG.", "POS_STD.DEV"],
    "rb_ppr": [
        "PPR_POS_RK",
        "PPR_POS_TIERS",
        "PLAYER NAME",
        "TEAM",
        "PPR_POS_BEST",
        "PPR_POS_WORST",
        "PPR_POS_AVG.",
        "PPR_POS_STD.DEV",
    ],
    "wr": ["PLAYER NAME", "TEAM", "POS_BEST", "POS_WORST", "POS_AVG.", "POS_STD.DEV"],
    "wr_ppr": [
        "PPR_POS_RK",
        "PPR_POS_TIERS",
        "PLAYER NAME",
        "TEAM",
        "PPR_POS_BEST",
        "PPR_POS_WORST",
        "PPR_POS_AVG.",
        "PPR_POS_STD.DEV",
    ],
    "te": ["PLAYER NAME", "TEAM", "POS_BEST", "POS_WORST", "POS_AVG.", "POS_STD.DEV"],
    "te_ppr": [
        "PPR_POS_RK",
        "PPR_POS_TIERS",
        "PLAYER NAME",
        "TEAM",
        "PPR_POS_BEST",
        "PPR_POS_WORST",
        "PPR_POS_AVG.",
        "PPR_POS_STD.DEV",
    ],
    "k": [
        "PLAYER NAME",
        "TEAM",
        "POS_BEST",
        "POS_WORST",
        "POS_AVG.",
        "POS_STD.DEV",
    ],
    "def": [
        "PLAYER NAME",
        "TEAM",
        "POS_BEST",
        "POS_WORST",
        "POS_AVG.",
        "POS_STD.DEV",
    ],
}

AVG_DF_COLUMNS = {
    "all": ["RK", "TIERS", "PLAYER NAME", "TEAM", "AVG_FAN PTS"],
    "all_ppr": [
        "PPR_RK",
        "PPR_TIERS",
        "PLAYER NAME",
        "TEAM",
        "PPR_AVG_FAN PTS",
        "AVG_PASS_YDS",
        "AVG_PASS_TDS",
        "AVG_REC",
        "AVG_REC_YDS",
        "AVG_REC_TDS",
        "AVG_RUSH_ATT",
        "AVG_RUSH_YDS",
        "AVG_RUSH_TDS",
    ],
    "qb": [
        "POS_RK",
        "POS_TIERS",
        "PLAYER NAME",
        "TEAM",
        "AVG_FAN PTS",
        "AVG_PASS_COMP",
        "AVG_PASS_ATT",
        "AVG_PASS_PCT",
        "AVG_YDS",
        "AVG_PASS_TDS",
        "AVG_PASS_INT",
        "AVG_RUSH_ATT",
        "AVG_RUSH_YDS",
        "AVG_RUSH_TDS",
        "AVG_SACK",
    ],
    "rb": ["POS_RK", "POS_TIERS", "PLAYER NAME", "TEAM", "AVG_FAN PTS"],
    "rb_ppr": [
        "PPR_POS_RK",
        "PPR_POS_TIERS",
        "PLAYER NAME",
        "TEAM",
        "PPR_AVG_FAN PTS",
        "AVG_RUSH_ATT",
        "AVG_RUSH_YDS",
        "AVG_RUSH_TDS",
        "AVG_TGT",
        "AVG_REC",
        "AVG_REC_YDS",
        "AVG_REC_TDS",
    ],
    "wr": ["POS_RK", "POS_TIERS", "PLAYER NAME", "TEAM", "AVG_FAN PTS"],
    "wr_ppr": [
        "PPR_POS_RK",
        "PPR_POS_TIERS",
        "PLAYER NAME",
        "TEAM",
        "PPR_AVG_FAN PTS",
        "AVG_TGT",
        "AVG_REC",
        "AVG_REC_YDS",
        "AVG_REC_TDS",
        "AVG_RUSH_ATT",
        "AVG_RUSH_YDS",
        "AVG_RUSH_TDS",
    ],
    "te": ["POS_RK", "POS_TIERS", "PLAYER NAME", "TEAM", "AVG_FAN PTS"],
    "te_ppr": [
        "PPR_POS_RK",
        "PPR_POS_TIERS",
        "PLAYER NAME",
        "TEAM",
        "PPR_AVG_FAN PTS",
        "AVG_TGT",
        "AVG_REC",
        "AVG_REC_YDS",
        "AVG_REC_TDS",
        "AVG_RUSH_ATT",
        "AVG_RUSH_YDS",
        "AVG_RUSH_TDS",
    ],
    "k": [
        "POS_RK",
        "POS_TIERS",
        "PLAYER NAME",
        "TEAM",
        "AVG_FAN PTS",
        "AVG_0-19",
        "AVG_20-29",
        "AVG_30-39",
        "AVG_40-49",
        "AVG_50+",
        "AVG_XPM",
        "AVG_XPA",
    ],
    "def": [
        "POS_RK",
        "POS_TIERS",
        "PLAYER NAME",
        "TEAM",
        "AVG_FAN PTS",
        "AVG_PTS VS.",
        "AVG_SACK",
        "AVG_SAFE",
        "AVG_INT",
        "AVG_FUMR",
        "AVG_DEF TD",
        "AVG_BLK KICK",
        "AVG_RET TD",
    ],
}

TOTAL_DF_COLUMNS = {
    k: [col.replace("AVG_", "") for col in v] for k, v in AVG_DF_COLUMNS.items()
}

SOS_URLs = {
    "full": "https://fftoolbox.fulltimefantasy.com/football/strength_of_schedule.cfm?type=e",
    "playoff": "https://fftoolbox.fulltimefantasy.com/football/strength_of_schedule.cfm?type=h",
    "season": "https://fftoolbox.fulltimefantasy.com/football/strength_of_schedule.cfm?type=b",
}

ADP_URLs = {
    "standard": "https://www.fantasypros.com/nfl/adp/overall.php",
    "ppr": "https://www.fantasypros.com/nfl/adp/ppr-overall.php",
}

REDZONE_URLs = {
    "rushing": "https://www.pro-football-reference.com/years/2023/redzone-rushing.htm",
    "receiving": "https://www.pro-football-reference.com/years/2023/redzone-receiving.htm",
}

REDZONE_RECEIVING_COLUMNS = [
    "PLAYER NAME",
    "20_YD_TGT",
    "20_YD_%TGT",
    "10_YD_TGT",
    "10_YD_%TGT",
]

REDZONE_RUSHING_COLUMNS = [
    "PLAYER NAME",
    "20_YD_ATT",
    "20_YD_%RUSH",
    "10_YD_ATT",
    "10_YD_%RUSH",
    "5_YD_ATT",
    "5_YD_%RUSH",
]
