URLs = {
    "all": "https://www.fantasypros.com/nfl/rankings/consensus-cheatsheets.php",
    "all_ppr": "https://www.fantasypros.com/nfl/rankings/ppr-cheatsheets.php",
    "qb": "https://www.fantasypros.com/nfl/rankings/qb-cheatsheets.php",
    "rb": "https://www.fantasypros.com/nfl/rankings/rb-cheatsheets.php",
    "rb_ppr": "https://www.fantasypros.com/nfl/rankings/ppr-rb-cheatsheets.php",
    "wr": "https://www.fantasypros.com/nfl/rankings/wr-cheatsheets.php",
    "wr_ppr": "https://www.fantasypros.com/nfl/rankings/ppr-wr-cheatsheets.php",
    "te": "https://www.fantasypros.com/nfl/rankings/te-cheatsheets.php",
    "te_ppr": "https://www.fantasypros.com/nfl/rankings/ppr-te-cheatsheets.php",
    "k": "https://www.fantasypros.com/nfl/rankings/k-cheatsheets.php",
    "def": "https://www.fantasypros.com/nfl/rankings/dst-cheatsheets.php",
}

AVG_DF_COLUMNS = {
    "all": ["RK", "TIERS", "PLAYER NAME", "TEAM", "AVG_FAN PTS"],
    "all_ppr": [
        "PPR_RK",
        "PPR_TIERS",
        "PLAYER NAME",
        "TEAM",
        "PPR_AVG_FAN PTS",
        "AVG_PASS_YDS",
        "AVG_PASS_TDS",
        "AVG_REC",
        "AVG_REC_YDS",
        "AVG_REC_TDS",
        "AVG_RUSH_ATT",
        "AVG_RUSH_YDS",
        "AVG_RUSH_TDS",
    ],
    "qb": [
        "POS_RK",
        "POS_TIERS",
        "PLAYER NAME",
        "TEAM",
        "AVG_FAN PTS",
        "AVG_PASS_COMP",
        "AVG_PASS_ATT",
        "AVG_PASS_PCT",
        "AVG_YDS",
        "AVG_PASS_TDS",
        "AVG_PASS_INT",
        "AVG_RUSH_ATT",
        "AVG_RUSH_YDS",
        "AVG_RUSH_TDS",
        "AVG_SACK",
    ],
    "rb": ["POS_RK", "POS_TIERS", "PLAYER NAME", "TEAM", "AVG_FAN PTS"],
    "rb_ppr": [
        "PPR_RK",
        "PPR_POS_TIERS",
        "PLAYER NAME",
        "TEAM",
        "PPR_AVG_FAN PTS",
        "AVG_RUSH_ATT",
        "AVG_RUSH_YDS",
        "AVG_RUSH_TDS",
        "AVG_TGT",
        "AVG_REC",
        "AVG_REC_YDS",
        "AVG_REC_TDS",
    ],
    "wr": ["POS_RK", "POS_TIERS", "PLAYER NAME", "TEAM", "AVG_FAN PTS"],
    "wr_ppr": [
        "PPR_RK",
        "PPR_POS_TIERS",
        "PLAYER NAME",
        "TEAM",
        "PPR_AVG_FAN PTS",
        "AVG_TGT",
        "AVG_REC",
        "AVG_REC_YDS",
        "AVG_REC_TDS",
        "AVG_RUSH_ATT",
        "AVG_RUSH_YDS",
        "AVG_RUSH_TDS",
    ],
    "te": ["POS_RK", "POS_TIERS", "PLAYER NAME", "TEAM", "AVG_FAN PTS"],
    "te_ppr": [
        "PPR_RK",
        "PPR_POS_TIERS",
        "PLAYER NAME",
        "TEAM",
        "PPR_AVG_FAN PTS",
        "AVG_TGT",
        "AVG_REC",
        "AVG_REC_YDS",
        "AVG_REC_TDS",
        "AVG_RUSH_ATT",
        "AVG_RUSH_YDS",
        "AVG_RUSH_TDS",
    ],
    "k": [
        "POS_RK",
        "POS_TIERS",
        "PLAYER NAME",
        "TEAM",
        "AVG_FAN PTS",
        "AVG_0-19",
        "AVG_20-29",
        "AVG_30-39",
        "AVG_40-49",
        "AVG_50+",
        "AVG_XPM",
        "AVG_XPA",
    ],
    "def": [
        "POS_RK",
        "POS_TIERS",
        "PLAYER NAME",
        "TEAM",
        "AVG_FAN PTS",
        "AVG_PTS VS.",
        "AVG_SACK",
        "AVG_SAFE",
        "AVG_INT",
        "AVG_FUMR",
        "AVG_DEF TD",
        "AVG_BLK KICK",
        "AVG_RET TD",
    ],
}

TOTAL_DF_COLUMNS = {
    k: [col.replace("AVG_", "") for col in v] for k, v in AVG_DF_COLUMNS.items()
}
